name: RandomTeleport
main: com.atomic.rtp.RandomTeleport
version: maven-version
description: Random Teleport
commands:
  randomtp:
    usage: /<command>
    description: Randomly teleport
    aliases: [rtp]